# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b486326c-acdd-4b54-846c-66bb2b9fd940";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1e1c7339-e378-448a-ac29-0b01ed47beaf".device = "/dev/disk/by-uuid/1e1c7339-e378-448a-ac29-0b01ed47beaf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DFB2-1189";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/32faab46-515e-4cbe-bfae-5c5f9d807687"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

